# - name: Create AMQ Streams Operator Group
#   k8s:
#     api_version: operators.coreos.com/v1
#     kind: OperatorGroup
#     name: workshop-operators
#     namespace: openshift-operators

# - name: Create AMQ Streams Subscription
#   k8s:
#     state: present
#     resource_definition: "{{ lookup('template', 'streams-subscription.yaml.j2') }}"

# - name: Wait for Streams operator to install
#   k8s_info:
#     api_version: apiextensions.k8s.io/v1
#     kind: CustomResourceDefinition
#     name: kafkas.kafka.strimzi.io
#   register: crd_streams
#   until: crd_streams.resources | default([]) | list | length == 1
#   retries: 10
#   delay: 30

- name: Create Cluster ConfigMap
  k8s:
    state: present
    namespace: '{{ utils_project }}'
    resource_definition: "{{ lookup('file', 'metrics-cm.yml') }}"

- name: Create AMQ Streams cluster
  k8s:
    state: present
    namespace: '{{ utils_project }}'
    resource_definition: "{{ lookup('template', 'amq-streams.yaml.j2') }}"

- name: "Wait for AMQ streams cluster be ready"
  k8s_info:
    kind: Pod
    label_selectors:
      - 'strimzi.io/name = my-cluster-entity-operator'
    namespace: '{{ utils_project }}'
  register: pod_status
  until: (pod_status | json_query("resources[0].status.containerStatuses[0].ready") | bool) == true
  retries: 40
  delay: 10